### PR TITLE
Fixing rerun analysis in calibration when missing file

### PR DESCRIPTION
**Pull request by guiguem**
Fixing CalibrationProcessor when missing file (Talia' suggestion)

### CODE REVIEW

**Comment by guiguem** [comment]
Includes @taliaweiss ' suggestion for having info as default in the logger.
Debug logs will be added using `-v`

**Comment by guiguem** [comment]
Thanks @taliaweiss !!
I just put the test script in the list of tests (tests.sh bash script), will check it passes in Travis and get this new release going :)
Thanks again!!

**Comment by taliaweiss** [comment]
Fantastic, thank you!

**Comment by guiguem** [comment]
As you might have seen, I put random things in the input and analysis trees... 
So feel free to revisit the test script in the future and provide something more meaningful, so the test can include assertion on the result of the calibration, for example.

**Comment by taliaweiss** [comment]
Sounds good – I will build out the test script a bit. I see you did the new release - that's great.

**Comment by taliaweiss** [comment]
@guiguem , what is the right way to switch between verbosity settings when configuring/running the processor?

**Comment by guiguem** [comment]
If you want to switch verbosity levels of the logger, you can do: 
```python
logger.setLevel(logging.DEBUG)
```
Maybe I don't quite understand the question.
You mean within an analysis script?

**Comment by taliaweiss** [comment]
Yes, within an analysis script. I had been hoping that the option to show the “debug” lines could be turned on or off, depending on whether one wants to see info about individual runs or just the calibration result at the end. My apologies if I wasn’t clear about this earlier!

**Comment by guiguem** [comment]
Then this is the way to do I think; say you have the two processors configure/run you want in more verbose mode, then do:
```python
[...]
logger.setLevel(logging.DEBUG)
proc.Configure(a_dict)
proc.Run()
logger.setLevel(logging.INFO)
[...]
```
Maybe you need to import the logging package first.

I tend to be okay with super verbose logs: it is better during official simulations/analysis to have more logs than not enough. :)
So imo you could just run the script in `-v` mode and select the information you need later on...

**Comment by taliaweiss** [comment]
That is helpful, thank you. Running the analysis in -v mode is a good idea. Setting the logger level as you showed above also worked for me. If I don't set `logger.setLevel(logging.INFO)`, then without the addition of -v, I do not see info output. But maybe that is how it is supposed to be.

**Pull request merged**
